### ISSUE TITLE
Error coming from `npm exec remix vite:dev`...Error: EPERM: operation not permitted, open 'C:\Users\HP\Downloads\shop-extension\vite.config.ts.timestamp-1731483459227-9603106566e29.mjs'

### ISSUE THREAD

**Issue by vaughnyb** [SuperZooper3/Voiceflow-In-Store-Shopify#2]
Im stuck on an error when i try to run npm run dev
Ive checked the properties of this file to be sure i have full permission but error still persist

heres the code:

C:\Users\HP\Downloads\shop-extension>npm run dev

> voiceflow-in-store@1.0.0 dev
> shopify app dev

╭─ info ───────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Using shopify.app.toml:                                                     │
│                                                                              │
│    • Org:             Hair Visions                                           │
│    • App:             voiceflow-in-store                                     │
│    • Dev store:       quickstart-31afecb9.myshopify.com                      │
│    • Update URLs:     Yes                                                    │
│                                                                              │
│   You can pass  `--reset`  to your command to reset your app configuration.  │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

14:37:19 │               remix │ Running pre-dev command: "npx prisma generate"
14:37:19 │            graphiql │ GraphiQL server started on port 3457
14:37:20 │ voiceflow-extension │ Draft updated successfully for extension: voiceflow-extension
14:37:24 │               remix │ Prisma schema loaded from prisma\schema.prisma
14:37:24 │               remix │ Datasource "db": SQLite database "dev.sqlite" at "file:dev.sqlite"
14:37:24 │               remix │
14:37:24 │               remix │ 1 migration found in prisma/migrations
14:37:24 │               remix │
14:37:24 │               remix │
14:37:24 │               remix │ No pending migrations to apply.
14:37:28 │    theme-extensions │
14:37:28 │    theme-extensions │ --------- Pushing theme files to App Ext. Host (cff970-LAPTOP-4R3ID001) (#138658611252)
 on quickstart-31afecb9.myshopify.com
14:37:28 │    theme-extensions │ Pushing theme...     0%
14:37:39 │               remix │ failed to load config from C:\Users\HP\Downloads\shop-extension\vite.config.ts
14:37:39 │               remix │ Error: EPERM: operation not permitted, open
'C:\Users\HP\Downloads\shop-extension\vite.config.ts.timestamp-1731483459227-9603106566e29.mjs'
14:37:39 │               remix │     at async open (node:internal/fs/promises:638:25)
14:37:39 │               remix │     at async Object.writeFile (node:internal/fs/promises:1208:14)
14:37:39 │               remix │     at async loadConfigFromBundledFile
(file:///C:/Users/HP/Downloads/shop-extension/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66982:5)
14:37:39 │               remix │     at async loadConfigFromFile
(file:///C:/Users/HP/Downloads/shop-extension/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66825:24)
14:37:39 │               remix │     at async resolveConfig
(file:///C:/Users/HP/Downloads/shop-extension/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66435:24)
14:37:39 │               remix │     at async _createServer
(file:///C:/Users/HP/Downloads/shop-extension/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:63048:18)
14:37:39 │               remix │     at async dev
(C:\Users\HP\Downloads\shop-extension\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
14:37:39 │               remix │     at async Object.viteDev
(C:\Users\HP\Downloads\shop-extension\node_modules\@remix-run\dev\dist\cli\commands.js:220:3)
14:37:39 │               remix │     at async Object.run
(C:\Users\HP\Downloads\shop-extension\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
14:37:39 │               remix │   errno: -4048,
14:37:39 │               remix │   code: 'EPERM',
14:37:39 │               remix │   syscall: 'open',
14:37:39 │               remix │   path:
'C:\\Users\\HP\\Downloads\\shop-extension\\vite.config.ts.timestamp-1731483459227-9603106566e29.mjs'
14:37:39 │               remix │ }

── external error ──────────────────────────────────────────────────────────────

Error coming from `npm exec remix vite:dev`

Command failed with exit code 1: npm exec remix vite:dev
failed to load config from C:\Users\HP\Downloads\shop-extension\vite.config.ts
Error: EPERM: operation not permitted, open
'C:\Users\HP\Downloads\shop-extension\vite.config.ts.timestamp-1731483459227-9603106566e29.mjs'
    at async open (node:internal/fs/promises:638:25)
    at async Object.writeFile (node:internal/fs/promises:1208:14)
    at async loadConfigFromBundledFile
(file:///C:/Users/HP/Downloads/shop-extension/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66982:5)
    at async loadConfigFromFile
(file:///C:/Users/HP/Downloads/shop-extension/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66825:24)
    at async resolveConfig
(file:///C:/Users/HP/Downloads/shop-extension/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66435:24)
    at async _createServer
(file:///C:/Users/HP/Downloads/shop-extension/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:63048:18)
    at async dev (C:\Users\HP\Downloads\shop-extension\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at async Object.viteDev
(C:\Users\HP\Downloads\shop-extension\node_modules\@remix-run\dev\dist\cli\commands.js:220:3)
    at async Object.run (C:\Users\HP\Downloads\shop-extension\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\HP\\Downloads\\shop-extension\\vite.config.ts.timestamp-1731483459227-9603106566e29.mjs'
}

────────────────────────────────────────────────────────────────────────────────

C:\Users\HP\Downloads\shop-extension>

**Comment by vaughnyb** [comment]
issue solved. turns out there was a hiding read only file changed to full control. issue disappered
